FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_HTTP_PORTS=8080 \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--project", "ViAgendamentos.Api", "--no-launch-profile"]
