// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViAgendamentos.Api.Data;
using ViAgendamentos.Api.Saloes;

#nullable disable

namespace ViAgendamentos.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930205317_CriaProfissionais")]
    partial class CriaProfissionais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role", new[] { "dona", "funcionaria" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AntecedenciaMinMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("antecedencia_min_minutos");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("AvisoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("aviso_minutos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("JanelaDias")
                        .HasColumnType("integer")
                        .HasColumnName("janela_dias");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("PassoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("passo_minutos");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Role>("Role")
                        .HasColumnType("role")
                        .HasColumnName("role");

                    b.Property<Guid>("SalaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("salao_id");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.HasKey("Id")
                        .HasName("pk_profissionais");

                    b.HasIndex("SalaoId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_profissionais_salao_email");

                    b.ToTable("profissionais", null, t =>
                        {
                            t.HasCheckConstraint("ck_profissionais_email_minusculo", "email = lower(email)");

                            t.HasCheckConstraint("ck_profissionais_email_preenchido", "email <> '' and email = btrim(email)");

                            t.HasCheckConstraint("ck_profissionais_nome_preenchido", "btrim(nome) <> ''");

                            t.HasCheckConstraint("ck_profissionais_phone", "phone ~ '^55[1-9]{2}[0-9]{8,9}$'");
                        });
                });

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Salao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fuso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_saloes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_saloes_slug");

                    b.ToTable("saloes", null, t =>
                        {
                            t.HasCheckConstraint("ck_saloes_phone", "phone ~ '^55[1-9]{2}[0-9]{8,9}$'");
                        });
                });

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Profissional", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Saloes.Salao", null)
                        .WithMany()
                        .HasForeignKey("SalaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profissionais_salao");
                });
#pragma warning restore 612, 618
        }
    }
}
