// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViAgendamentos.Api.Data;

#nullable disable

namespace ViAgendamentos.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930143149_CriaSaloes")]
    partial class CriaSaloes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Salao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fuso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_saloes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_saloes_slug");

                    b.ToTable("saloes", null, t =>
                        {
                            t.HasCheckConstraint("ck_saloes_whatsapp", "whatsapp ~ '^55[1-9]{2}[0-9]{8,9}$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
