// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViAgendamentos.Api.Clientes;
using ViAgendamentos.Api.Data;
using ViAgendamentos.Api.GoogleAgenda;
using ViAgendamentos.Api.Saloes;

#nullable disable

namespace ViAgendamentos.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origem", new[] { "link", "profissional" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role", new[] { "dona", "funcionaria" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_conexao", new[] { "ativa", "revogada" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_chaves_protecao");

                    b.ToTable("chaves_protecao", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_claims_user_id");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuario_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_logins_user_id");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuario_tokens");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("ViAgendamentos.Api.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Origem>("CriadaPor")
                        .HasColumnType("origem")
                        .HasColumnName("criada_por");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid>("SalaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("salao_id");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_clientes_usuario_id");

                    b.HasIndex("SalaoId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_clientes_salao_email");

                    b.HasIndex("SalaoId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uq_clientes_salao_usuario");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_email_minusculo", "email = lower(email)");

                            t.HasCheckConstraint("ck_clientes_email_preenchido", "email <> '' and email = btrim(email)");

                            t.HasCheckConstraint("ck_clientes_link_exige_email_e_phone", "criada_por <> 'link' or (email is not null and phone is not null)");

                            t.HasCheckConstraint("ck_clientes_nome_preenchido", "btrim(nome) <> ''");

                            t.HasCheckConstraint("ck_clientes_phone", "phone ~ '^55[1-9]{2}[0-9]{8,9}$'");
                        });
                });

            modelBuilder.Entity("ViAgendamentos.Api.GoogleAgenda.ConexaoGoogle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConectadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conectado_em");

                    b.Property<string>("GoogleEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_email");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<byte[]>("RefreshTokenCifrado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_cifrado");

                    b.Property<StatusConexao>("Status")
                        .HasColumnType("status_conexao")
                        .HasColumnName("status");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("text")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id")
                        .HasName("pk_conexoes_google");

                    b.HasIndex("ProfissionalId")
                        .IsUnique()
                        .HasDatabaseName("uq_conexoes_google_profissional");

                    b.ToTable("conexoes_google", (string)null);
                });

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AntecedenciaMinMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("antecedencia_min_minutos");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("AvisoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("aviso_minutos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("JanelaDias")
                        .HasColumnType("integer")
                        .HasColumnName("janela_dias");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("PassoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("passo_minutos");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Role>("Role")
                        .HasColumnType("role")
                        .HasColumnName("role");

                    b.Property<Guid>("SalaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("salao_id");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_profissionais");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_profissionais_usuario_id");

                    b.HasIndex("SalaoId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_profissionais_salao_email");

                    b.HasIndex("SalaoId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uq_profissionais_salao_usuario");

                    b.ToTable("profissionais", null, t =>
                        {
                            t.HasCheckConstraint("ck_profissionais_email_minusculo", "email = lower(email)");

                            t.HasCheckConstraint("ck_profissionais_email_preenchido", "email <> '' and email = btrim(email)");

                            t.HasCheckConstraint("ck_profissionais_nome_preenchido", "btrim(nome) <> ''");

                            t.HasCheckConstraint("ck_profissionais_phone", "phone ~ '^55[1-9]{2}[0-9]{8,9}$'");
                        });
                });

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Salao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fuso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_saloes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_saloes_slug");

                    b.ToTable("saloes", (string)null);
                });

            modelBuilder.Entity("ViAgendamentos.Api.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_usuarios_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_normalized_user_name");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("ViAgendamentos.Api.Clientes.Cliente", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Saloes.Salao", null)
                        .WithMany()
                        .HasForeignKey("SalaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_salao");

                    b.HasOne("ViAgendamentos.Api.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_usuario");
                });

            modelBuilder.Entity("ViAgendamentos.Api.GoogleAgenda.ConexaoGoogle", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Saloes.Profissional", null)
                        .WithOne()
                        .HasForeignKey("ViAgendamentos.Api.GoogleAgenda.ConexaoGoogle", "ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conexoes_google_profissional");
                });

            modelBuilder.Entity("ViAgendamentos.Api.Saloes.Profissional", b =>
                {
                    b.HasOne("ViAgendamentos.Api.Saloes.Salao", null)
                        .WithMany()
                        .HasForeignKey("SalaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profissionais_salao");

                    b.HasOne("ViAgendamentos.Api.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_profissionais_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
